import numpy as np

SIZE = (600, 800)
WIDTH, HEIGHT = SIZE
PADDING = 50
BOARD_X = PADDING
BOARD_Y = PADDING
BOARD_WIDTH = WIDTH - (2 * PADDING)
BOARD_HEIGHT = HEIGHT - (2 * PADDING)
FPS = 60
TITLE = "Sheep and Wolf - Pygame Simulation"

SEUIL_COLLISION = 2.5

# Sheep parameters 
NUM_SHEEPS = 15

S_TURNING_SPEED = np.radians(8)
S_NOISE_ANGLE = np.radians(10)
S_MOVING_SPEED = 0.3
S_CHARACTERISTIC_LENGTH = 5

S_REPULSION_RADIUS = 15.0
S_ORIENTATION_RADIUS = 1.0
S_ATTRACTION_RADIUS = 15.0
S_WOLF_REPULSION_RADIUS = 30.0

# Wolf parameters
NUM_WOLVES = 7

W_TURNING_SPEED = np.radians(5)
W_NOISE_ANGLE = np.radians(5)
W_MOVING_SPEED = 1.5
W_CHARACTERISTIC_LENGTH = 5

W_REPULSION_RADIUS = 2.5
W_ORIENTATION_RADIUS = 0.01
W_ATTRACTION_RADIUS = 300.0
W_WOLF_HUNTING_RADIUS = 300.0
